//! IEEE MA-L OUI vendor lookup.
//!
//! The registry table and the `OnceLock` + `HashMap` loading strategy are
//! ArcScan's, reused because they are the right shape for the problem: the full
//! registry (~39k prefixes) is embedded as a compact `PREFIX\tVendor` table
//! generated by `scripts/generate_oui.py`, parsed once on first use, and looked
//! up in O(1) thereafter. Nothing is fetched at runtime, so vendor
//! identification works on an isolated customer network.
//!
//! What is new here is [`tidy_vendor`]. The registry is a legal document: it
//! says `XEROX CORPORATION`, `Cisco Systems, Inc`, `TP-LINK TECHNOLOGIES
//! CO.,LTD.`. A Manufacturer column full of that is hard to scan, and the
//! column is one of the most useful things on screen, so trailing legal-entity
//! suffixes are removed and shouted names are cased normally. The rewrite is
//! presentational only -- it never substitutes one company for another and
//! never invents a name for an unknown prefix.

use std::collections::HashMap;
use std::sync::OnceLock;

const OUI_DATA: &str = include_str!("oui_data.tsv");

static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

fn map() -> &'static HashMap<&'static str, &'static str> {
    MAP.get_or_init(|| {
        let mut m = HashMap::with_capacity(40_000);
        for line in OUI_DATA.lines() {
            if let Some((prefix, vendor)) = line.split_once('\t') {
                m.insert(prefix, vendor);
            }
        }
        m
    })
}

/// Trailing legal-entity words, longest first so `Co., Ltd.` is removed as one
/// unit rather than leaving a stray `Co.` behind.
const SUFFIXES: [&str; 26] = [
    "co., ltd.",
    "co.,ltd.",
    "co., ltd",
    "co.,ltd",
    "co ltd",
    "pty ltd",
    "incorporated",
    "corporation",
    "company",
    "limited",
    "gmbh & co. kg",
    "gmbh",
    "s.a.s.",
    "s.a.r.l.",
    "s.p.a.",
    "a/s",
    "b.v.",
    "n.v.",
    "llc",
    "l.l.c.",
    "plc",
    "ltd.",
    "ltd",
    "inc.",
    "inc",
    "corp.",
];

/// Look up the vendor for a MAC address, tidied for display.
///
/// Accepts any common separator style. Returns `None` for an unknown prefix or
/// a malformed address, because an empty Manufacturer cell is the honest answer
/// and a guess would be worse than a blank.
pub fn lookup(mac: &str) -> Option<String> {
    raw_lookup(mac).map(tidy_vendor)
}

/// The registry's own wording, before any tidying.
fn raw_lookup(mac: &str) -> Option<&'static str> {
    let hex: String = mac
        .chars()
        .filter(|c| c.is_ascii_hexdigit())
        .take(6)
        .collect::<String>()
        .to_ascii_uppercase();
    if hex.len() != 6 {
        return None;
    }
    map().get(hex.as_str()).copied()
}

/// Make a registry organisation name readable in a dense table.
///
/// Two rules, applied in order, and both deliberately conservative:
///
/// 1. Strip trailing legal-entity suffixes, repeatedly, so `Cisco Systems, Inc`
///    becomes `Cisco Systems` and `TP-LINK TECHNOLOGIES CO.,LTD.` loses its
///    tail. Stripping stops if it would empty the name, so a company actually
///    called `Limited` keeps its name.
/// 2. If the name contains no lowercase letter at all, it is being shouted
///    rather than spelled; case it as a title. Tokens of three characters or
///    fewer are left alone, because those are acronyms -- `HP`, `LG`, `IBM`,
///    `TP` in `TP-LINK` -- and title-casing them would be a misspelling.
pub fn tidy_vendor(name: &str) -> String {
    let mut text = name.trim().to_string();

    loop {
        let lower = text.to_ascii_lowercase();
        let trimmed = SUFFIXES.iter().find_map(|suffix| {
            let base = lower.strip_suffix(suffix)?;
            // Only a suffix that stands as its own word: `Incheon` must not
            // lose an `Inc`.
            let boundary_ok = base
                .chars()
                .next_back()
                .is_none_or(|c| c.is_whitespace() || c == ',' || c == '.' || c == '-');
            boundary_ok.then(|| text[..base.len()].trim_end_matches([' ', ',', '.', '-']))
        });
        match trimmed {
            Some(next) if !next.is_empty() && next.len() < text.len() => {
                text = next.to_string();
            }
            _ => break,
        }
    }

    if !text.chars().any(|c| c.is_ascii_lowercase()) {
        text = title_case(&text);
    }
    text
}

/// Title-case a shouted name, preserving short tokens as acronyms.
fn title_case(text: &str) -> String {
    text.split(' ')
        .map(|word| {
            word.split_inclusive(['-', '/', '&'])
                .map(|segment| {
                    // `split_inclusive` keeps the separator on the segment, so
                    // measure and re-case only the letters before it.
                    let (letters, tail) = match segment.chars().next_back() {
                        Some(c) if c == '-' || c == '/' || c == '&' => {
                            segment.split_at(segment.len() - c.len_utf8())
                        }
                        _ => (segment, ""),
                    };
                    let cased = if letters.chars().count() <= 3 {
                        letters.to_string()
                    } else {
                        let mut chars = letters.chars();
                        match chars.next() {
                            Some(first) => {
                                format!("{first}{}", chars.as_str().to_ascii_lowercase())
                            }
                            None => String::new(),
                        }
                    };
                    format!("{cased}{tail}")
                })
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_registry_loads_and_is_the_size_it_should_be() {
        assert!(
            map().len() > 30_000,
            "only {} prefixes loaded; oui_data.tsv looks truncated",
            map().len()
        );
    }

    #[test]
    fn separator_style_does_not_matter() {
        let expected = lookup("00:00:00:11:22:33");
        assert!(expected.is_some());
        assert_eq!(lookup("00-00-00-11-22-33"), expected);
        assert_eq!(lookup("000000112233"), expected);
        assert_eq!(lookup("00:00:00"), expected);
        assert_eq!(lookup("aa:bb:cc"), lookup("AA:BB:CC"));
    }

    #[test]
    fn malformed_input_resolves_to_nothing() {
        for bad in ["", "zz", "gg:hh:ii", "00:00", "not a mac"] {
            assert_eq!(lookup(bad), None, "accepted {bad:?}");
        }
    }

    #[test]
    fn the_vendors_technicians_meet_every_day_resolve() {
        // Prefixes taken from the embedded registry. Each assertion is on the
        // company, not on the exact registry wording, because the wording is
        // what `tidy_vendor` exists to normalise.
        let cases = [
            ("00:06:5B", "Dell"),
            ("00:00:00", "Xerox"),
            ("00:1A:A0", "Dell"),
            ("00:1B:78", "Hewlett"),
            ("00:00:0C", "Cisco"),
            ("00:1C:B3", "Apple"),
            ("00:1B:21", "Intel"),
            ("00:80:77", "Brother"),
        ];
        for (mac, expected) in cases {
            let vendor = lookup(mac).unwrap_or_else(|| panic!("{mac} did not resolve"));
            assert!(
                vendor
                    .to_ascii_lowercase()
                    .contains(&expected.to_ascii_lowercase()),
                "{mac} resolved to {vendor:?}, expected it to name {expected}"
            );
        }
    }

    #[test]
    fn legal_suffixes_are_removed() {
        assert_eq!(tidy_vendor("Dell Inc."), "Dell");
        assert_eq!(tidy_vendor("Dell Inc"), "Dell");
        assert_eq!(tidy_vendor("Cisco Systems, Inc"), "Cisco Systems");
        assert_eq!(tidy_vendor("Ubiquiti Inc"), "Ubiquiti");
        assert_eq!(tidy_vendor("Lenovo (Beijing) Limited"), "Lenovo (Beijing)");
        assert_eq!(tidy_vendor("Netgear Inc."), "Netgear");
        assert_eq!(tidy_vendor("Sophos Ltd"), "Sophos");
        assert_eq!(tidy_vendor("Siemens AG GmbH"), "Siemens AG");
        assert_eq!(tidy_vendor("Synology Incorporated"), "Synology");
        assert_eq!(tidy_vendor("Fortinet, Inc."), "Fortinet");
    }

    #[test]
    fn a_shouted_name_is_cased_but_acronyms_are_kept() {
        assert_eq!(tidy_vendor("XEROX CORPORATION"), "Xerox");
        assert_eq!(
            tidy_vendor("TP-LINK TECHNOLOGIES CO.,LTD."),
            "TP-Link Technologies"
        );
        assert_eq!(tidy_vendor("LG ELECTRONICS INC"), "LG Electronics");
        assert_eq!(tidy_vendor("HP INC."), "HP");
        assert_eq!(tidy_vendor("IBM"), "IBM");
        assert_eq!(
            tidy_vendor("SAMSUNG ELECTRO-MECHANICS"),
            "Samsung Electro-Mechanics"
        );
        assert_eq!(
            tidy_vendor("ZYXEL COMMUNICATIONS CORP."),
            "Zyxel Communications"
        );
    }

    #[test]
    fn a_name_that_already_reads_properly_is_left_alone() {
        assert_eq!(tidy_vendor("Brother Industries"), "Brother Industries");
        assert_eq!(tidy_vendor("VMware"), "VMware");
        assert_eq!(tidy_vendor("ASUSTek COMPUTER"), "ASUSTek COMPUTER");
        assert_eq!(tidy_vendor("Raspberry Pi Trading"), "Raspberry Pi Trading");
        assert_eq!(
            tidy_vendor("Aruba, a Hewlett Packard Enterprise Company"),
            "Aruba, a Hewlett Packard Enterprise"
        );
    }

    #[test]
    fn tidying_never_empties_a_name() {
        for name in ["Inc.", "Limited", "Corp.", "LLC", "Ltd"] {
            assert_eq!(tidy_vendor(name), name, "{name} was stripped away");
        }
    }

    #[test]
    fn a_word_that_merely_ends_in_a_suffix_survives() {
        assert_eq!(tidy_vendor("Incheon"), "Incheon");
        assert_eq!(tidy_vendor("Plcnet"), "Plcnet");
    }

    #[test]
    fn every_registry_entry_tidies_to_something_non_empty() {
        // The whole table, because a single entry that tidied to "" would show
        // as a blank Manufacturer cell for a vendor that is actually known.
        for (prefix, vendor) in map().iter() {
            let tidied = tidy_vendor(vendor);
            assert!(
                !tidied.trim().is_empty(),
                "{prefix} ({vendor:?}) tidied to nothing"
            );
        }
    }
}
